### ISSUE TITLE
[求助]根据文档安装过程中出现命令无法找到等报错

### ISSUE THREAD

**Issue by LinYuanovo** [zhinjs/zhin#123]
**Bug 描述**
根据文档中的三种方式创建项目均会出现报错

**复现步骤**
1. 通过 cli 指令创建
2. 通过 npm 指令创建
3. 通过模板仓库创建

**实际情况**
如果可以，请提供截图描述

**运行环境:**
 - OS: Windows、Linux
 - Node版本: 20.15.0

**近10条日志:**

> zhin-app@1.0.0 start:zhin
> start-zhin

sh: line 1: start-zhin: command not found
Error: Command failed: npm run start
    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at checkExecSyncError (node:child_process:890:11)
    at execSync (node:child_process:962:15)
    at install (/root/.npm/_npx/ce99ce5353c1f606/node_modules/create-zhin/lib/index.js:242:38)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async start (/root/.npm/_npx/ce99ce5353c1f606/node_modules/create-zhin/lib/index.js:266:5) {
  status: 127,
  signal: null,
  output: [ null, null, null ],
  pid: 1219781,
  stdout: null,
  stderr: null
}

**Comment by lc-cn** [comment]
3.x 版本文档仅支持查看 start部分，其他部分将逐渐补充
