### ISSUE TITLE
 [ERROR] [icqq] - [禁止登录]登录失败，建议升级最新版本后重试，或通过问题反馈与我们联系。

### ISSUE THREAD

**Issue by linonetwo** [zhinjs/zhin#5]
手机上扫码是成功允许登录了的，然后回车出现这个

**Comment by linonetwo** [comment]
还有这个问题

TypeError: Cannot read properties of undefined (reading 'plugins')
    at OneBot.start (/Users/linonetwo/Desktop/repo/qq-bot/node_modules/.pnpm/@zhinjs+plugin-onebot@0.0.3/node_modules/@zhinjs/plugin-onebot/lib/index.js:582:35)
    at Plugin.install (/Users/linonetwo/Desktop/repo/qq-bot/node_modules/.pnpm/@zhinjs+plugin-onebot@0.0.3/node_modules/@zhinjs/plugin-onebot/lib/index.js:644:20)
    at Plugin.mount (/Users/linonetwo/Desktop/repo/qq-bot/node_modules/.pnpm/zhin@2.0.2-80/node_modules/zhin/lib/plugin.js:27:45)
    at installPlugin (/Users/linonetwo/Desktop/repo/qq-bot/node_modules/.pnpm/zhin@2.0.2-80/node_modules/zhin/lib/context.js:125:24)
    at Proxy.plugin (/Users/linonetwo/Desktop/repo/qq-bot/node_modules/.pnpm/zhin@2.0.2-80/node_modules/zhin/lib/context.js:136:9)
    at /Users/linonetwo/Desktop/repo/qq-bot/node_modules/.pnpm/zhin@2.0.2-80/node_modules/zhin/lib/zhin.js:422:22
    at Array.forEach (<anonymous>)
    at Proxy.start (/Users/linonetwo/Desktop/repo/qq-bot/node_modules/.pnpm/zhin@2.0.2-80/node_modules/zhin/lib/zhin.js:420:41)
    at Object.<anonymous> (/Users/linonetwo/Desktop/repo/qq-bot/node_modules/.pnpm/zhin@2.0.2-80/node_modules/zhin/worker.js:12:6)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)

**Comment by linonetwo** [comment]
cli 生成的配置文件


port: 8086
adapters:
  icqq:
    bots:
      - uin: 1287688945
        password: -
        platform: 1
        master: 563061713
        data_dir: data
self_url: localhost
data_dir: data
plugin_dir: plugins
plugins:
  watcher: /Users/linonetwo/Desktop/repo/qq-bot
log_level: info
services: {}
delay:
  prompt: 60000
logConfig:
  appenders:
    consoleOut:
      type: console
    saveFile:
      type: file
      filename: /Users/linonetwo/Desktop/repo/qq-bot/logs.log
  categories:
    default:
      appenders:
        - consoleOut
        - saveFile
      level: info


能不把密码放在这里吗？想放在一个 。env 文件里

**Comment by linonetwo** [comment]
没看到在哪里配置启用的插件列表，不想用这个插件了发现没地方关，packagejson 里去掉之后就说找不到了

[2023-02-26T23:42:34.460] [WARN] [zhin] - Error: Cannot find module '@zhinjs/plugin-database'
Require stack:
- /Users/linonetwo/Desktop/repo/qq-bot/node_modules/.pnpm/@zhinjs+plugin-qa@0.0.9/node_modules/@zhinjs/plugin-qa/lib/index.js

**Comment by linonetwo** [comment]
一开始不应该用 cli 安装插件，不然配置里不会列出来

**Comment by linonetwo** [comment]
删掉 device。json 后，修改

        platform: 3

就可以登录了

**Comment by linonetwo** [comment]
填了密码后每次还是要扫码

**Comment by lc-cn** [comment]
> 填了密码后每次还是要扫码

将配置文件中的uin改为self_id，这个是cli生成的配置文件有问题(@zhinjs/cli最新版已经改了)

**Comment by lc-cn** [comment]
> 没看到在哪里配置启用的插件列表，不想用这个插件了发现没地方关，packagejson 里去掉之后就说找不到了
> 
> [2023-02-26T23:42:34.460] [WARN] [zhin] - Error: Cannot find module '@zhinjs/plugin-database' Require stack:
> 
> * /Users/linonetwo/Desktop/repo/qq-bot/node_modules/.pnpm/@zhinjs+plugin-qa@0.0.9/node_modules/@zhinjs/plugin-qa/lib/index.js

这是因为qa以来的数据库插件没正常安装，所以启用qa失败了，建议如果不需要，可以先卸载@zhinjs/plugin-qa

**Comment by lc-cn** [comment]
> 还有这个问题
> 
> TypeError: Cannot read properties of undefined (reading 'plugins') at OneBot.start (/Users/linonetwo/Desktop/repo/qq-bot/node_modules/.pnpm/@zhinjs+plugin-onebot@0.0.3/node_modules/@zhinjs/plugin-onebot/lib/index.js:582:35) at Plugin.install (/Users/linonetwo/Desktop/repo/qq-bot/node_modules/.pnpm/@zhinjs+plugin-onebot@0.0.3/node_modules/@zhinjs/plugin-onebot/lib/index.js:644:20) at Plugin.mount (/Users/linonetwo/Desktop/repo/qq-bot/node_modules/.pnpm/zhin@2.0.2-80/node_modules/zhin/lib/plugin.js:27:45) at installPlugin (/Users/linonetwo/Desktop/repo/qq-bot/node_modules/.pnpm/zhin@2.0.2-80/node_modules/zhin/lib/context.js:125:24) at Proxy.plugin (/Users/linonetwo/Desktop/repo/qq-bot/node_modules/.pnpm/zhin@2.0.2-80/node_modules/zhin/lib/context.js:136:9) at /Users/linonetwo/Desktop/repo/qq-bot/node_modules/.pnpm/zhin@2.0.2-80/node_modules/zhin/lib/zhin.js:422:22 at Array.forEach () at Proxy.start (/Users/linonetwo/Desktop/repo/qq-bot/node_modules/.pnpm/zhin@2.0.2-80/node_modules/zhin/lib/zhin.js:420:41) at Object. (/Users/linonetwo/Desktop/repo/qq-bot/node_modules/.pnpm/zhin@2.0.2-80/node_modules/zhin/worker.js:12:6) at Module._compile (node:internal/modules/cjs/loader:1159:14)

@zhinjs/plugin-onebot 已弃用

**Comment by linonetwo** [comment]
可以了，之前那些插件都是 cli 装的，后来我重新 init 了一次，没选它们了

**Comment by linonetwo** [comment]
还是每次都要滑块

重新创建后，滑块完成后输入 token 无响应

```
[2023-03-03T14:49:22.455] [MARK] [aPad:x] - 114.x:8080 connected
[2023-03-03T14:49:22.573] [MARK] [aPad:x] - 收到滑动验证码，请访问以下地址完成滑动，并从网络响应中取出ticket输入：https://ssl.captcha.qq.com/template/wireless_mqq_captcha.html?xxx&clientype=1&apptype=2
t03mMRojjfj00XfoaG9sJW8SQGC0ezLPT1zvrSr4BNY0MPC8IDzOwmELiiIU
t03mMRojjfj00XfoaG9sJW8SQGC0ezLPT1zvrSr4BNY0MPC8IDzOw

```

**Comment by linonetwo** [comment]
上述已修复，最新报错为

[2023-03-13T17:13:53.009] [WARN] [icqq] - token失效: [禁止登录]登录失败，建议升级最新版本后重试，或通过问题反馈与我们联系。(错误码：45)
[2023-03-13T17:13:53.010] [ERROR] [icqq] - [禁止登录]登录失败，建议升级最新版本后重试，或通过问题反馈与我们联系。

**Comment by linonetwo** [comment]
上述已修复，最新报错为

[2023-03-13T17:13:53.009] [WARN] [icqq] - token失效: [禁止登录]登录失败，建议升级最新版本后重试，或通过问题反馈与我们联系。(错误码：45)
[2023-03-13T17:13:53.010] [ERROR] [icqq] - [禁止登录]登录失败，建议升级最新版本后重试，或通过问题反馈与我们联系。

**Comment by linonetwo** [comment]
需要一个这种情况下清空 token 的对话选项

**Comment by linonetwo** [comment]
```
[2023-03-13T17:16:27.013] [WARN] [icqq] - token失效: [禁止登录]请使用手Q扫描二维码或短信登录。(错误码：238)
[2023-03-13T17:16:27.014] [ERROR] [icqq] - [禁止登录]请使用手Q扫描二维码或短信登录。
```

Platform 为 3 时是这个报错

**Comment by linonetwo** [comment]
改为 platform: 4 ，并使用密保手机发送短信方式登录后解决。
