### ISSUE TITLE
TAR_BAD_ARCHIVE: Unrecognized archive format

### ISSUE THREAD

**Issue by linonetwo** [zhinjs/zhin#6]
% npm init zhin

  Create Zhin

✔ Project name: … tw-qq-bot
Error: TAR_BAD_ARCHIVE: Unrecognized archive format
    at Unpack.warn (/Users/linonetwo/.npm/_npx/f2b2dbed5e8bf168/node_modules/tar/lib/warn-mixin.js:21:40)
    at Unpack.warn (/Users/linonetwo/.npm/_npx/f2b2dbed5e8bf168/node_modules/tar/lib/unpack.js:229:18)
    at Unpack.<anonymous> (/Users/linonetwo/.npm/_npx/f2b2dbed5e8bf168/node_modules/tar/lib/parse.js:83:14)
    at Unpack.emit (node:events:525:35)
    at [emit] (/Users/linonetwo/.npm/_npx/f2b2dbed5e8bf168/node_modules/tar/lib/parse.js:303:12)
    at [maybeEnd] (/Users/linonetwo/.npm/_npx/f2b2dbed5e8bf168/node_modules/tar/lib/parse.js:426:17)
    at [consumeChunk] (/Users/linonetwo/.npm/_npx/f2b2dbed5e8bf168/node_modules/tar/lib/parse.js:434:21)
    at Unpack.write (/Users/linonetwo/.npm/_npx/f2b2dbed5e8bf168/node_modules/tar/lib/parse.js:385:25)
    at Unpack.end (/Users/linonetwo/.npm/_npx/f2b2dbed5e8bf168/node_modules/tar/lib/parse.js:505:14)
    at IncomingMessage.onend (node:internal/streams/readable:705:10) {
  recoverable: false,
  cwd: '/Users/linonetwo/Desktop/repo/qq-bot/tw-qq-bot',
  code: 'TAR_BAD_ARCHIVE',
  tarCode: 'TAR_BAD_ARCHIVE'
}

**Comment by lc-cn** [comment]
非zhin报错，不予理会
